name: Update Playwright Snapshots

on:
  issue_comment:
    types: [created, edited]

jobs:
  update-snapshots:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'please update snapshots') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Update Snapshots
      uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        test_folder: ui-tests
